version: 2.1

orbs:
  node: circleci/node@5.0.3

workflows:
  build-and-test:
    jobs:
      - node/test:
          app-dir: frontend
          version: "16.18"
          pkg-manager: yarn
      - node/run:
          app-dir: frontend
          version: "16.18"
          pkg-manager: yarn
          yarn-run: lint -w
